SELECT DISTINCT CART_ID
FROM (SELECT CART_ID, NAME FROM CART_PRODUCTS WHERE NAME = 'MILK') M 
     JOIN (SELECT CART_ID, NAME FROM CART_PRODUCTS WHERE NAME = 'YOGURT') Y
     USING(CART_ID)
ORDER BY 1;