(SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS DATE_FORMAT, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE 
WHERE SALES_DATE LIKE '2022_03%')
UNION
(SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS DATE_FORMAT, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE 
WHERE SALES_DATE LIKE '2022_03%')
ORDER BY 1,2,3;