SELECT O.ANIMAL_ID, NAME
FROM ANIMAL_OUTS O JOIN
    (SELECT DATEDIFF(O.DATETIME, I.DATETIME) AS DATE, O.ANIMAL_ID
    FROM ANIMAL_OUTS O JOIN ANIMAL_INS I ON O.ANIMAL_ID = I.ANIMAL_ID ORDER BY DATE DESC LIMIT 2) V 
    ON O.ANIMAL_ID = V.ANIMAL_ID
ORDER BY V.DATE DESC; 