# SELECT ROUND(AVG(
#     CASE 
#         WHEN (LENGTH <= 10 || LENGTH IS NULL) THEN 10
#     ELSE LENGTH
#     END
# ), 2) AVERAGE_LENGTH FROM FISH_INFO;

SELECT ROUND(AVG(IFNULL(LENGTH, 10)), 2) AVERAGE_LENGTH FROM FISH_INFO;