SELECT R1.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO R1, (SELECT MAX(FAVORITES) MAX_F, FOOD_TYPE FROM REST_INFO GROUP BY FOOD_TYPE) R2
WHERE R1.FOOD_TYPE = R2.FOOD_TYPE AND FAVORITES = MAX_F
ORDER BY 1 DESC;