# SELECT 
#     ID,
#     CASE 
#         WHEN RANKING <= COUNT * 0.25 THEN 'CRITICAL'
#         WHEN RANKING <= COUNT * 0.5 THEN 'HIGH'
#         WHEN RANKING <= COUNT * 0.75 THEN 'MEDIUM'
#         ELSE 'LOW'
#     END AS COLONY_NAME
# FROM (SELECT ID, RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANKING FROM ECOLI_DATA) E1, (SELECT COUNT(*) COUNT FROM ECOLI_DATA) E2
# ORDER BY 1;

SELECT ID,
        CASE
            WHEN NO = 1 THEN 'CRITICAL'
            WHEN NO = 2 THEN 'HIGH'
            WHEN NO = 3 THEN 'MEDIUM'
            ELSE 'LOW'
        END AS COLONY_NAME
FROM (SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS NO FROM ECOLI_DATA) E
ORDER BY 1;