SELECT P.PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT) * PRICE TOTAL_SALES
FROM FOOD_PRODUCT P JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE SUBSTR(PRODUCE_DATE,1,7) = '2022-05'
GROUP BY PRODUCT_ID
ORDER BY 3 DESC, 1 ASC;