SELECT F.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER FROM FIRST_HALF GROUP BY 1) F
        JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER FROM JULY GROUP BY 1) J
        ON F.FLAVOR = J.FLAVOR
ORDER BY F.TOTAL_ORDER + J.TOTAL_ORDER DESC
LIMIT 3;