WITH RECURSIVE CTE AS
(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM CTE
    WHERE HOUR < 23
)

SELECT HOUR, COUNT(DATETIME) COUNT
FROM CTE C LEFT JOIN (SELECT HOUR(DATETIME) DATETIME FROM ANIMAL_OUTS) A ON C.HOUR = A.DATETIME
GROUP BY HOUR
ORDER BY HOUR;