-- 문제 : RARITY가 RARE인 아이템들의 다음 업그레이트 아이템의 ITEM_ID, ITEM_NAME, RARITY출력 / ITEM_ID기준 내림차순
-- 업그레이드 : ITEM_A가 ITEM_B의 PARNET아이템이라면, ITEM_A를 ITEM_B로 업그레이드 가능 
-- 즉, RARE인 아이템의 ID를 PARNET_ITEM_ID의 값으로 갖는 ITEM_ID를 추적하기

SELECT F.ITEM_ID, F.ITEM_NAME, F.RARITY
FROM ITEM_TREE T JOIN ITEM_INFO F ON T.ITEM_ID = F.ITEM_ID
WHERE T.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
ORDER BY F.ITEM_ID DESC;