-- 문제 : DEVELOPERS 테이블에서 Python이나 C#스킬을 가진 개발자 정보 조회 / 결과는 ID기준 오름차순
-- 조회할 정보 : ID, EMAIL, FIRST_NAME, LAST_NAME

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS 
WHERE 
    SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') OR
    SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')
ORDER BY ID ASC;