SELECT YEAR, MAX_SIZE - SIZE_OF_COLONY YEAR_DEV, ID
FROM ECOLI_DATA, (SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAX_SIZE FROM ECOLI_DATA GROUP BY YEAR) E2
WHERE YEAR(DIFFERENTIATION_DATE) = YEAR
ORDER BY 1, 2;