-- 요약 : 판매일이 2022년 1월인 도서의 카테고리별 판매량 구하기 / 카테고리 기준 오름차순 정렬
SELECT B.CATEGORY, SUM(S.SALES) AS 'TOTAL_SALES'
FROM BOOK B JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 01
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;